[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[unix_http_server]
file=/var/run/supervisor.sock

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[program:health-bot]
command=python run.py
directory=/app
user=nobody
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/var/log/supervisor/health-bot.log
environment=PATH="/app/venv/bin"
; Detener proceso gracefully
stopasgroup=true
killasgroup=true
; Reintentos
startsecs=10
startretries=3
